use_frameworks!

target 'Languager_Example' do
  pod 'Languager', :path => '../'

  target 'Languager_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
